---
version : '3'

networks:
  frontend:
  backend:

services:
  worker:
    container_name: worker
    image: alpine:latest
    tty: true
    volumes:
    - .:/var/www:cached
    networks:
    - backend

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
    - .:/var/www:cached
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./conf.d/:/etc/nginx/conf.d/
    - ./sites/:/etc/nginx/sites-available/
    ports:
    - 80:80
    command: nginx
    depends_on:
    - php-fpm
    networks:
    - frontend
    - backend

  php-fpm:
    container_name: php-fpm
    image: php:fpm-alpine
    volumes:
    - .:/var/www:cached
    networks:
    - backend

